FROM nginx:alpine

# Remove default nginx files
RUN rm -rf /usr/share/nginx/html/*

# Copy all static files
COPY nevoblog.html /usr/share/nginx/html/nevoblog.html
COPY index.css /usr/share/nginx/html/index.css
COPY P1.png /usr/share/nginx/html/P1.png
COPY PNG.jpeg /usr/share/nginx/html/PNG.jpeg
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]